
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://tnkadvphfswtzoltehpk.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRua2FkdnBoZnN3dHpvbHRlaHBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5MzM5OTYsImV4cCI6MjA5MjUwOTk5Nn0.v764MJbNLF6xRJCd78VTSCvFnSl_1ppm1GUnUxv1eBQ';

const supabase = createClient(supabaseUrl, supabaseAnonKey);

const jobs = [
  { role: "Research Assistant-Rice Breeding", company_name: "INVICTA AGRITECH INDIA PVT LTD", education: "SSC", sector: "Agriculture" },
  { role: "Assistant Breeder-Rice", company_name: "INVICTA AGRITECH INDIA PVT LTD", education: "SSC", sector: "Agriculture" },
  { role: "Site Safety Manager", company_name: "Greenways BioEnergy Private Limited", education: "DEGREE OR EQUIVALENT", sector: "Engineering" },
  { role: "Manager - Accounts and Finance", company_name: "Greenways BioEnergy Private Limited", education: "DEGREE OR EQUIVALENT", sector: "Finance" },
  { role: "Senior Executive -Accounts and Finance", company_name: "Greenways BioEnergy Private Limited", education: "PG OR EQUIVALENT", sector: "Finance" },
  { role: "DTDC (Processing Staff)", company_name: "DTDC", education: "SSC", sector: "Logistics" },
  { role: "Relationship manager", company_name: "Indusind(reliance) nippon life insurance", education: "DEGREE OR EQUIVALENT", sector: "Finance" },
  { role: "welders", company_name: "Medplusindia", education: "SSC", sector: "Manufacturing" },
  { role: "CNC Operator", company_name: "Medplusindia", education: "INTER MEDIATE OR EQUIVALENT", sector: "Manufacturing" },
  { role: "Loaders / Helpers", company_name: "Medplusindia", education: "SSC", sector: "Logistics" },
  { role: "Technician & Helpers", company_name: "Icleantech", education: "SSC", sector: "Engineering" },
  { role: "Multicuisine Chef", company_name: "Unknown", education: "SSC", sector: "Hospitality" },
  { role: "Lab Assistants", company_name: "Unknown", education: "INTER MEDIATE OR EQUIVALENT", sector: "Healthcare" },
  { role: "Hospital Ward Boys", company_name: "Unknown", education: "SSC", sector: "Healthcare" },
  { role: "Staff Nurse", company_name: "Unknown", education: "DEGREE OR EQUIVALENT", sector: "Healthcare" },
  { role: "Inventory Coordinator", company_name: "Unknown", education: "SSC", sector: "Logistics" },
  { role: "Structural Grinding Technician / Grinder", company_name: "Ganaengineering", education: "INTER MEDIATE OR EQUIVALENT", sector: "Engineering" },
  { role: "Data Analyst", company_name: "Unknown", education: "DEGREE OR EQUIVALENT", sector: "Technology" },
  { role: "MACHINE OPERATER", company_name: "Unknown", education: "SSC", sector: "Manufacturing" },
  { role: "Trainee", company_name: "Jamppharma", education: "DEGREE OR EQUIVALENT", sector: "Pharmaceuticals" },
  { role: "Helper Operator / Apprentice / Warehouse Operations Supervisor", company_name: "Hindustan Coca-cola Beverages", education: "INTER MEDIATE OR EQUIVALENT", sector: "FMCG" },
  { role: "Housekeeping Supervisior", company_name: "Trishalalaminates", education: "INTER MEDIATE OR EQUIVALENT", sector: "Manufacturing" },
  { role: "FITTERS", company_name: "Unknown", education: "INTER MEDIATE OR EQUIVALENT", sector: "Manufacturing" },
  { role: "ELECTRICIANS", company_name: "Unknown", education: "INTER MEDIATE OR EQUIVALENT", sector: "Engineering" },
  { role: "Mechanical Design Lead", company_name: "Sickle Innovations Pvt.Ltd", education: "B.TECH", sector: "Agriculture Machinery" },
  { role: "Senior RnD Engineer – Farm Machinery", company_name: "Sickle Innovations Pvt Ltd", education: "PG OR EQUIVALENT", sector: "Agriculture Machinery" },
  { role: "Production Technician", company_name: "Sickle Innovations Pvt Ltd", education: "INTER MEDIATE OR EQUIVALENT", sector: "Manufacturing" },
  { role: "MIG Welder", company_name: "Sickle Innovations Pvt Ltd", education: "SSC", sector: "Manufacturing" },
  { role: "JR. EXECUTIVE", company_name: "Msnlabs", education: "DEGREE OR EQUIVALENT", sector: "Pharmaceuticals" },
  { role: "Project Manager", company_name: "Your volta services private limited", education: "B.TECH", sector: "Technology" },
  { role: "Quality Analyst", company_name: "Your Volta services private limited", education: "DEGREE OR EQUIVALENT", sector: "Technology" },
  { role: "iOS Developer", company_name: "Your Volta services private limited", education: "B.TECH", sector: "Technology" },
  { role: "Android Developer", company_name: "Your Volta services private limited", education: "B.TECH", sector: "Technology" },
  { role: "6TON PACKAGE BOILER OPERATOR", company_name: "Unknown", education: "INTER MEDIATE OR EQUIVALENT", sector: "Manufacturing" },
  { role: "Ground Coordinator", company_name: "Delhivery Ltd.", education: "SSC", sector: "Logistics" },
  { role: "Rotory Operator", company_name: "Lohiya Confectioneries Pvt Ltd", education: "INTER MEDIATE OR EQUIVALENT", sector: "Food" },
  { role: "Cutting Line Operator", company_name: "Lohiya Confectioneries Pvt Ltd", education: "INTER MEDIATE OR EQUIVALENT", sector: "Food" },
  { role: "Welder", company_name: "Lohiya Confectioneries Pvt Ltd", education: "SSC", sector: "Food" },
  { role: "Packing Machine Operator", company_name: "Lohiya Confectioneries Pvt Ltd", education: "INTER MEDIATE OR EQUIVALENT", sector: "Food" },
  { role: "Packing Machine -Fitter", company_name: "Lohiya Confectioneries Pvt Ltd", education: "B.TECH", sector: "Food" },
  { role: "Oven Operator", company_name: "Lohiya Confectioneries Pvt Ltd", education: "INTER MEDIATE OR EQUIVALENT", sector: "Food" },
  { role: "Mixing Operator", company_name: "Lohiya Confectioneries Pvt Ltd", education: "INTER MEDIATE OR EQUIVALENT", sector: "Food" },
  { role: "Quality Officer", company_name: "Trishala Laminates Pvt. Ltd.", education: "DEGREE OR EQUIVALENT", sector: "Manufacturing" },
  { role: "QC - Analyst", company_name: "Ciropharmagroup", education: "DEGREE OR EQUIVALENT", sector: "Pharmaceuticals" },
  { role: "Granuation Operator", company_name: "Ciropharmagroup", education: "INTER MEDIATE OR EQUIVALENT", sector: "Pharmaceuticals" },
  { role: "Production - Diploma Freshers", company_name: "Aspiro Pharma Limited", education: "INTER MEDIATE OR EQUIVALENT", sector: "Pharmaceuticals" },
  { role: "Production Filling Operators", company_name: "Aspiro Pharma Limited", education: "INTER MEDIATE OR EQUIVALENT", sector: "Pharmaceuticals" },
  { role: "PHYSIOTHERAPIST BPT", company_name: "Unknown", education: "DEGREE OR EQUIVALENT", sector: "Healthcare" },
  { role: "MSC NURSING ALL CATEGORIES 3-5", company_name: "Unknown", education: "PG OR EQUIVALENT", sector: "Healthcare" },
  { role: "Waiters & Food Supply Staff (Male – 10 Positions)", company_name: "Unknown", education: "SSC", sector: "Hospitality" },
  { role: "Ward Boy (Male – 20 Positions)", company_name: "Unknown", education: "SSC", sector: "Healthcare" },
  { role: "Housekeeping Staff", company_name: "Unknown", education: "SSC", sector: "Hospitality" },
  { role: "Marketing Officer", company_name: "Nova Agri Sciences Private Limited", education: "DEGREE OR EQUIVALENT", sector: "Agriculture" },
  { role: "Biomedical Engineer", company_name: "Unknown", education: "B.TECH", sector: "Healthcare" },
  { role: "Audiologist", company_name: "Unknown", education: "DEGREE OR EQUIVALENT", sector: "Healthcare" },
  { role: "Physiotherapist MPT", company_name: "Unknown", education: "PG OR EQUIVALENT", sector: "Healthcare" },
  { role: "Staff Nurse (GNM)", company_name: "Unknown", education: "DEGREE OR EQUIVALENT", sector: "Healthcare" },
  { role: "BSC Nursing Staff", company_name: "Unknown", education: "DEGREE OR EQUIVALENT", sector: "Healthcare" },
  { role: "CT Technician", company_name: "Unknown", education: "INTER MEDIATE OR EQUIVALENT", sector: "Healthcare" },
  { role: "MRI Technicians", company_name: "Unknown", education: "INTER MEDIATE OR EQUIVALENT", sector: "Healthcare" },
  { role: "OT Technicians", company_name: "Unknown", education: "INTER MEDIATE OR EQUIVALENT", sector: "Healthcare" },
  { role: "QA Documentation Executive", company_name: "Pulse Nutri Science Pvt Ltd", education: "DEGREE OR EQUIVALENT", sector: "Nutraceuticals" },
  { role: "Production Executive", company_name: "Pulse Nutri Science Pvt Ltd", education: "B.TECH", sector: "Nutraceuticals" },
  { role: "Staff Nurse (B.Sc Nursing)", company_name: "Unknown", education: "DEGREE OR EQUIVALENT", sector: "Healthcare" },
  { role: "Electrical Maintenance Executive", company_name: "Pulse Nutriscience Pvt Ltd", education: "INTER MEDIATE OR EQUIVALENT", sector: "Nutraceuticals" },
  { role: "R&D Chemist/QC Chemist", company_name: "LTR LIFE SCIENCES PRIVATE LIMITED", education: "DEGREE OR EQUIVALENT", sector: "Pharmaceuticals" },
  { role: "10th (or) Intermediate", company_name: "IN N OUT FOOD INGREDIENTS", education: "SSC", sector: "Food" },
  { role: "Electrical Apprentices", company_name: "IN N OUT FOOD INGREDIENTS", education: "SSC", sector: "Food" },
  { role: "Trainees", company_name: "Rane Madras Limited-BCD", education: "B.TECH", sector: "Automotive" },
  { role: "Accounts data entry operator", company_name: "Gangakaveri", education: "INTER MEDIATE OR EQUIVALENT", sector: "Agriculture" },
  { role: "Ffs machine operator", company_name: "Gangakaveri", education: "INTER MEDIATE OR EQUIVALENT", sector: "Agriculture" },
  { role: "Security persons", company_name: "Satya surya aluminium industry ltd", education: "SSC", sector: "Manufacturing" },
  { role: "Electrical and mechanical", company_name: "Satya surya aluminium industry Ltd", education: "SSC", sector: "Manufacturing" },
  { role: "Quality checker", company_name: "Satya surya aluminium industry Ltd", education: "B.TECH", sector: "Manufacturing" },
  { role: "Data Entry Operator", company_name: "MAHADEVI AGRO MILLS PRIVATE LIMITED", education: "INTER MEDIATE OR EQUIVALENT", sector: "Agriculture" },
  { role: "MECHANICAL ENGINEER", company_name: "Unknown", education: "B.TECH", sector: "Engineering" },
  { role: "Weigh Bridge Operator", company_name: "MAHADEVI AGRO MILLS PRIVATE LIMITED", education: "INTER MEDIATE OR EQUIVALENT", sector: "Agriculture" },
  { role: "security guard", company_name: "sandhya poultry farm", education: "SSC", sector: "Agriculture" },
  { role: "CNC Plasma Operator", company_name: "Ganaengineering", education: "INTER MEDIATE OR EQUIVALENT", sector: "Engineering" },
  { role: "Fitter", company_name: "Gana engineering", education: "B.TECH", sector: "Engineering" },
  { role: "QC Chemist", company_name: "Neospark Drugs and Chemicals Private Limited", education: "B.TECH", sector: "Pharmaceuticals" },
  { role: "Jr Fitter", company_name: "Neospark Drugs and Chemicals private limited", education: "B.TECH", sector: "Pharmaceuticals" },
  { role: "Accounts - Trainee", company_name: "Vickrobiopharma", education: "B.TECH", sector: "Pharmaceuticals" },
  { role: "Warehouse Trainee", company_name: "Vickro Biopharma", education: "SSC", sector: "Pharmaceuticals" },
  { role: "Production - Trainee", company_name: "Vickrobiopharma", education: "SSC", sector: "Pharmaceuticals" },
  { role: "QA", company_name: "Vickrobiopharma", education: "DEGREE OR EQUIVALENT", sector: "Pharmaceuticals" },
  { role: "Microbiology - Analyst", company_name: "Vickrobiopharma", education: "DEGREE OR EQUIVALENT", sector: "Pharmaceuticals" },
  { role: "QC - Trainee", company_name: "Vickrobiopharma", education: "B.TECH", sector: "Pharmaceuticals" },
  { role: "Developer", company_name: "Kalpratech", education: "B.TECH", sector: "Technology" },
  { role: "Sales Recruiter", company_name: "Kalpratech", education: "DEGREE OR EQUIVALENT", sector: "Technology" },
  { role: "Python Developer", company_name: "Kalpratech", education: "B.TECH", sector: "Technology" },
  { role: "Non IT", company_name: "Kalpratech", education: "B.TECH", sector: "Technology" },
  { role: "Java Developer", company_name: "Kalpratech", education: "B.TECH", sector: "Technology" },
  { role: "Content Writing", company_name: "Unknown", education: "DEGREE OR EQUIVALENT", sector: "Content" },
  { role: "Video Editing", company_name: "Unknown", education: "INTER MEDIATE OR EQUIVALENT", sector: "Content" },
  { role: "Production Executive", company_name: "Sanzymebiologics", education: "DEGREE OR EQUIVALENT", sector: "Pharmaceuticals" },
  { role: "ITI/Diploma Electrician", company_name: "Sanzymebiologics", education: "B.TECH", sector: "Pharmaceuticals" },
  { role: "Electrical engineer", company_name: "Sanzymebiologics", education: "B.TECH", sector: "Pharmaceuticals" },
  { role: "Asst.Manager - Quality Control", company_name: "Sanzymebiologics", education: "B.TECH", sector: "Pharmaceuticals" },
  { role: "All Subject Teachers", company_name: "Unknown", education: "DEGREE OR EQUIVALENT", sector: "Education" },
  { role: "Manager-production Nutraceuticals", company_name: "Dxn2u", education: "PG OR EQUIVALENT", sector: "Health & Wellness" },
  { role: "Trainee-QC", company_name: "Dxn2u", education: "B.TECH", sector: "Health & Wellness" },
  { role: "Assistant Civil Engineer", company_name: "Dxn2u", education: "B.TECH", sector: "Health & Wellness" },
  { role: "Boiler Operator", company_name: "Dxn2u", education: "INTER MEDIATE OR EQUIVALENT", sector: "Health & Wellness" },
  { role: "Semi-Skilled Operator-Production", company_name: "Dxn2u", education: "INTER MEDIATE OR EQUIVALENT", sector: "Health & Wellness" },
  { role: "Senior Software Engineer", company_name: "Unknown", education: "B.TECH", sector: "Technology" },
  { role: "Skilled-Operator-Production", company_name: "Dxn2u", education: "INTER MEDIATE OR EQUIVALENT", sector: "Health & Wellness" },
  { role: "Lab Assistant", company_name: "Jodasexpoim", education: "INTER MEDIATE OR EQUIVALENT", sector: "Pharmaceuticals" },
  { role: "Office Boy", company_name: "Jodasexpoim", education: "SSC", sector: "Pharmaceuticals" },
  { role: "Security Guards", company_name: "Egis-roi", education: "SSC", sector: "Engineering" },
  { role: "Executive / Sr.Executive Process Instrumentation", company_name: "Jodasexpoim", education: "DEGREE OR EQUIVALENT", sector: "Pharmaceuticals" },
  { role: "Executive / Sr.Executive Process Mechanical", company_name: "Jodasexpoim", education: "DEGREE OR EQUIVALENT", sector: "Pharmaceuticals" },
  { role: "eCommerce Analyst", company_name: "Isnap", education: "DEGREE OR EQUIVALENT", sector: "Technology" },
  { role: "Cloud / DevOps Engineer", company_name: "Citrux", education: "B.TECH", sector: "Technology" },
  { role: "Trainee Operator Warehouse department", company_name: "Jodasexpoim", education: "B.TECH", sector: "Pharmaceuticals" },
  { role: "Trainee Operator - Production department", company_name: "Jodasexpoim", education: "B.TECH", sector: "Pharmaceuticals" },
  { role: "MLOps Engineer", company_name: "Citrux", education: "B.TECH", sector: "Technology" },
  { role: "Data Analyst", company_name: "Citrux", education: "B.TECH", sector: "Technology" },
  { role: "Toll collector", company_name: "Egis-roi", education: "SSC", sector: "Engineering" },
  { role: "Data Scientist", company_name: "Citrux", education: "B.TECH", sector: "Technology" },
  { role: "Machine Learning Engineer", company_name: "Citrux", education: "B.TECH", sector: "Technology" },
  { role: "Inside Sales - Business Development", company_name: "Isnap", education: "DEGREE OR EQUIVALENT", sector: "Technology" },
  { role: "Operator, Electrician, Fitter", company_name: "Sitaramspinners", education: "B.TECH", sector: "Textiles" },
  { role: "Analytical Chemistry Study Assistant", company_name: "Vivobio", education: "SSC", sector: "Biotechnology" },
  { role: "Business Development (BD) Executives", company_name: "Vivobio", education: "DEGREE OR EQUIVALENT", sector: "Biotechnology" },
  { role: "Research Associate", company_name: "Vivobio", education: "PG OR EQUIVALENT", sector: "Biotechnology" },
  { role: "AI Career Optimization Specialist", company_name: "Applywizz", education: "PG OR EQUIVALENT", sector: "Technology" },
  { role: "Senior Software Engineer", company_name: "Applywizz", education: "B.TECH", sector: "Technology" },
  { role: "AI Trainee", company_name: "Applywizz", education: "B.TECH", sector: "Technology" },
  { role: "AI Solutions Consultant – SaaS Sales", company_name: "Applywizz", education: "B.TECH", sector: "Technology" },
  { role: "Associate Software Developer", company_name: "Applywizz", education: "B.TECH", sector: "Technology" },
  { role: "Associate Data Engineer", company_name: "Applywizz", education: "B.TECH", sector: "Technology" },
  { role: "Full Stack Software Engineer", company_name: "Applywizz", education: "B.TECH", sector: "Technology" },
  { role: "UI/UX Designer", company_name: "Applywizz", education: "B.TECH", sector: "Technology" },
];

async function seed() {
  console.log(`Starting seed: ${jobs.length} jobs...`);
  
  // Insert in chunks of 50
  for (let i = 0; i < jobs.length; i += 50) {
    const chunk = jobs.slice(i, i + 50);
    const { data, error } = await supabase.from('jobs').insert(chunk).select();
    
    if (error) {
      console.error('Error seeding chunk:', error.message);
    } else {
      console.log(`Successfully seeded ${data?.length || 0} jobs...`);
    }
  }
  
  console.log('Seed complete.');
}

seed();
